name: 'test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  cos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: '3.9'

      - name: Install COSCMD
        run: |
          pip install coscmd
          pip install coscmd -U

      - name: Setup COSCMD
        uses: ./
        with:
          util-type: coscmd
          secret-id: ${{ secrets.SECRET_ID }}
          secret-key: ${{ secrets.SECRET_KEY }}
          bucketname-appid: ${{ secrets.BUCKET }}
          region: ${{ secrets.REGION }}

      - name: Deploy
        run: coscmd upload action.yml /

  oss:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup OSSUtil
        uses: ./
        with:
          util-type: ossutil
          endpoint-oss: ${{ secrets.ENDPOINT }}
          access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}

      - name: Deploy
        run: ossutil cp -rf action.yml oss://szfkx-web-demo/
